name: wizard_world
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^2.5.0
  dio: ^5.4.1
  retrofit_generator: ^8.1.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.10
  meta: ^1.10.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit: ^4.1.0
  freezed: ^2.4.7
  build_runner: ^2.4.8
  freezed_annotation: ^2.4.1
  flutter_lints: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: EduTAS
      fonts:
        - asset: fonts/EduTASBeginner-Bold.ttf
        - asset: fonts/EduTASBeginner-Medium.ttf
        - asset: fonts/EduTASBeginner-Regular.ttf
        - asset: fonts/EduTASBeginner-SemiBold.ttf
        - asset: fonts/magic_school_two.ttf
    - family: MagicSchool
      fonts:
        - asset: fonts/magic_school_two.ttf
